DROP TABLE ORDERS;
DROP TABLE CUSTOMERS;
DROP TABLE EMPLOYEES;
DROP TABLE RESTAURANTS;

CREATE TABLE CUSTOMERS(CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT, CUSTOMER_EMAIL VARCHAR(40), FNAME VARCHAR(20), LNAME VARCHAR(20), PASSWORD VARCHAR(60));

CREATE TABLE RESTAURANTS(RESTAURANT_ID INT PRIMARY KEY AUTO_INCREMENT, RESTAURANT_NAME VARCHAR(30));
CREATE TABLE EMPLOYEES(EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,EMP_EMAIL VARCHAR(40), EMP_FNAME VARCHAR(20), EMP_LNAME VARCHAR(20), EMP_PASSWORD VARCHAR(60),
RESTAURANT_NAME VARCHAR(30));

CREATE TABLE ORDERS(ORDER_ID INT PRIMARY KEY AUTO_INCREMENT, TIME_CREATED DATETIME, TIME_COLLECTED DATETIME, RATING INT(1) DEFAULT 0, ORDER_STATUS VARCHAR(15) DEFAULT "pending", CUSTOMER_ID INT, EMPLOYEE_ID INT, RESTAURANT_NAME VARCHAR(30) ,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID));

INSERT INTO RESTAURANTS VALUES(1,"Spur");
INSERT INTO RESTAURANTS VALUES(2,"KFC");




