DROP TABLE ORDERS;
DROP TABLE CUSTOMERS;
DROP TABLE EMPLOYEES;

CREATE TABLE CUSTOMERS(CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT, CUSTOMER_EMAIL VARCHAR(20), FNAME VARCHAR(20), LNAME VARCHAR(20), PASSWORD VARCHAR(15));

CREATE TABLE EMPLOYEES(EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT, EMP_FNAME VARCHAR(20), EMP_LNAME VARCHAR(20), EMP_PASSWORD VARCHAR(15));

CREATE TABLE ORDERS(ORDER_ID INT PRIMARY KEY AUTO_INCREMENT, TIME_CREATED TIME, RATING INT(1), ORDER_STATUS VARCHAR(15), CUSTOMER_ID INT, EMPLOYEE_ID INT, 
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID), 
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID));
